# Generated by Django 4.2.23 on 2025-08-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenwiseai', '0002_audiorecording_audio_file_audiorecording_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiorecording',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='recordings/'),
        ),
    ]
