# Generated by Django 4.2.23 on 2025-08-24 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenwiseai', '0003_alter_audiorecording_audio_file'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='audiorecording',
            table='audio_recording',
        ),
    ]
